### ISSUE TITLE
protobuf版本号冲突

### ISSUE THREAD

**Issue by xiaoyaolangzhi** [chenyiwan/chatglm-6b-fine-tuning#4]
![image](https://user-images.githubusercontent.com/15037766/229133202-05286217-f6b0-4723-8969-93b88c908db8.png)
我用的python是3.10的，必须要3.7的吗？

**Comment by chenyiwan** [comment]
这个应该不影响 ，你换一下试试

**Comment by xiaoyaolangzhi** [comment]
重新安装了下，可以了
