### ISSUE TITLE
save_model_path目录下没有保存数据

### ISSUE THREAD

**Issue by xiaoyaolangzhi** [chenyiwan/chatglm-6b-fine-tuning#5]
![image](https://user-images.githubusercontent.com/15037766/229288136-0d19ed94-9c54-4964-a2cf-82d140cb2520.png)
这是什么情况？

**Comment by chenyiwan** [comment]
你这个数据量也太小了吧，就一行啊。

**Comment by xiaoyaolangzhi** [comment]
多谢提醒，问题已解决！
